openapi: '3.1.1'
info:
  title: Book Store
  version: '1.0'
servers:
  - url: https://reimagined-space-succotash-6p96j46q4wq2xr5j-3001.app.github.dev/
    
       
paths:
  /v1/rentals/list:
    get:
      description: One stop destination for any book you read
      responses:
        '200':
          description: OK

  /v1/users/list:
    get:
      description: list all users
      responses:
        '200':
          description: OK

  /v1/users/create:
    post:
      description: create a new user
      responses:
        '200':
          description: OK